In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
arr = np.random.randint(1, 51, size=10)

media = arr.mean()
desvio = arr.std()
print(arr)
print(f'A média da matriz é :{media}')
print(f'O desvio padrão é :{desvio}')

[ 6 49 15 46 34 26 35 40 23 20]
A média da matriz é :29.4
O desvio padrão é :13.116401945655676


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)
print(arr)
teste = arr[arr <=0.5 ] = np.sqrt(arr[arr <=0.5])
print(teste)

[0.31973944 0.8862463  0.94135857 0.23947019 0.84288445 0.13756704
 0.31099004 0.11620745 0.67571444 0.95007334]
[0.56545507 0.48935692 0.37090031 0.55766481 0.34089214]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
Matriz_3D = np.random.rand(3,3,3)

maximo = np.amax(Matriz_3D, axis = 1)
#Vai criar o array máximo utilizando as colunas do Matriz_3D e posicionando o máximo nas linhas 
#amax serve para calcular o máximo de um array

print(Matriz_3D)

print(f'\n O máximo de cada matriz: {maximo}')
  

[[[0.38595261 0.62340635 0.97880998]
  [0.60878714 0.12402053 0.54330469]
  [0.14228333 0.65156979 0.89180379]]

 [[0.20357051 0.55127682 0.97992195]
  [0.09327877 0.61913994 0.21478471]
  [0.37072137 0.63723703 0.70747305]]

 [[0.57455824 0.81851987 0.57590964]
  [0.08096386 0.02440049 0.60837272]
  [0.67196995 0.65119926 0.00767095]]]

 O máximo de cada matriz: [[0.60878714 0.65156979 0.97880998]
 [0.37072137 0.63723703 0.97992195]
 [0.67196995 0.81851987 0.60837272]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)
print(matriz)

soma = np.sum(matriz, axis = 1)
print(f'\n Soma das linhas: \n {soma}')

media = np.mean(matriz, axis =1)
print(f'\n Média das linhas: \n {media}')

resolucao = soma - media

print(f'\n Subtração das médias de cada linha: {resolucao}')
2,17527162 
0,43505432 

[[0.09823495 0.45084018 0.37702836 0.28980042 0.92433856]
 [0.66550676 0.32312734 0.26311657 0.39567733 0.23529474]
 [0.08373201 0.060177   0.20185228 0.03058524 0.7825697 ]
 [0.0818231  0.69752782 0.91882353 0.60922776 0.82558507]
 [0.10833956 0.4493457  0.85729108 0.81668729 0.12994006]]

 Soma das linhas: 
 [2.14024248 1.88272273 1.15891623 3.13298728 2.3616037 ]

 Média das linhas: 
 [0.4280485  0.37654455 0.23178325 0.62659746 0.47232074]

 Subtração das médias de cada linha: [1.71219398 1.50617819 0.92713299 2.50638983 1.88928296]
Out[24]: (0, 43505432)

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)
print(f'Matriz:\n {matriz}')


diagonal = np.diagonal(matriz)
print(f'\n Diagonal: \n {diagonal}')

diagonal_2 = np.diagonal(np.fliplr(matriz ))
print(f'\n Diagonal 2: \n {diagonal_2}')

media = np.mean([diagonal, diagonal_2])
print(f'\n Media:\n {media}')

desvio = np.std([diagonal, diagonal_2])
print(f'\n Desvio padrão:\n {desvio}')


Matriz:
 [[0.60070623 0.69469424 0.08916316 0.34912569]
 [0.23951329 0.72900191 0.89148687 0.83000052]
 [0.5132727  0.79915551 0.94576638 0.29620598]
 [0.89715646 0.09222466 0.39530572 0.08069597]]

 Diagonal: 
 [0.60070623 0.72900191 0.94576638 0.08069597]

 Diagonal 2: 
 [0.34912569 0.89148687 0.79915551 0.89715646]

 Media:
 0.6616368771589823

 Desvio padrão:
 0.28533918723839347


In [0]:
diagonal_2 = np.diag(matriz)
print(f'\n Diagonal 2: \n {diagonal_2}')


 Diagonal 2: 
 [0.54190869 0.66260067 0.48082111 0.20164837]
